---

- name: Install Apache
  apt:
    name: apache2 
    state: latest

- name: Start Apache
  service:
    name: apache2
    state: started
  register: verif

- name: Verif Apache
  debug:
    msg: "{{verif.status}}"

- name: Mettre en place index
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restart Apache
    - Petit curl la base
    - Verif du curl
