---
- name: Creation User
  hosts: webserver
  remote_user: root
  vars_files:
    - "../vars/{{env}}_vars.yml"
    - "../vars/{{env}}_secret.yml"
  tasks:
    - name: Ajouter un user
      user:
        name: "{{user}}"
        password: "{{ password | password_hash('sha512') }}"
        uid: 1001
    



